'use strict';
const STATUS = {afazer:'A fazer',fazendo:'Fazendo',concluido:'Concluído',cancelado:'Cancelado'};
const RDO_FIELDS = ['Data','Dia da Semana','Obra','Empresa','Cidade','Local da Obra','Descrição do Local','Tempo/Clima','Jornada','DSS Horário','DSS Ministrado Por','DSS Tema','Atividades do Dia','Efetivo Total','Efetivo por Função','Colaboradores Presentes','Equipamentos Utilizados','Veículos Leves','Veículos/Equipamentos Parados','Eventos de Segurança','Eventos de Meio Ambiente','Observações do Dia','Apontador','Fotos','RDO Nº'];
const clone = x => JSON.parse(JSON.stringify(x));
const uid = () => globalThis.crypto.randomUUID();
const today = () => {const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const active = t => ['afazer','fazendo'].includes(t.status);
const overdue = (t,date=today()) => active(t)&&!!t.due&&t.due<date;
function requireWork(s,id){if(!s.works.some(w=>w.id===id))throw Error('Obra não encontrada.');}
function validateTask(s,t){requireWork(s,t.obraId);if(!t.title.trim()||!t.owner.trim()||!t.sector.trim())throw Error('Preencha assunto, responsável e setor.');if(!(t.status in STATUS))throw Error('Estado desconhecido: exige conciliação.');if(!['alta','media','baixa'].includes(t.priority))throw Error('Prioridade inválida.');if(!t.created||!t.due||t.due<t.created)throw Error('O prazo não pode ser anterior ao lançamento.');}
function saveTask(s,t,reason='') {validateTask(s,t);const old=s.tasks.find(x=>x.id===t.id);if(old&&old.obraId!==t.obraId)throw Error('Não é permitido transferir o registro entre obras.');if(((t.status==='cancelado'&&old?.status!=='cancelado')||(old&&!active(old)&&active(t)))&&!reason.trim())throw Error('Informe a justificativa do cancelamento ou reabertura.');const next=clone(t);next.history=clone(old?.history||[]);next.history.push({at:new Date().toISOString(),from:old?.status||null,to:t.status,reason,action:old?'edição':'criação'});if(old)s.tasks[s.tasks.indexOf(old)]=next;else s.tasks.push(next);return next;}
function saveMeeting(s,m){requireWork(s,m.obraId);if(!m.title.trim()||!m.date||!m.time||!m.participants.trim())throw Error('Preencha título, data, hora e participantes.');const ids=new Set(m.taskIds);const tasks=s.tasks.filter(t=>ids.has(t.id));if(tasks.length!==ids.size||tasks.some(t=>t.obraId!==m.obraId))throw Error('Pauta incompatível com a obra.');const meeting={...clone(m),id:uid(),createdAt:new Date().toISOString(),snapshot:clone(tasks)};delete meeting.taskIds;s.meetings.push(meeting);return meeting;}
function saveRdo(s,r){requireWork(s,r.obraId);if(!r.fields.Data||!r.fields.Apontador?.trim()||!r.fields['Atividades do Dia']?.trim())throw Error('Informe data, apontador e atividades.');const old=s.rdos.find(x=>x.id===r.id);if(old&&old.obraId!==r.obraId)throw Error('Obra incompatível.');if(r.fields['Efetivo Total']!==''&&r.fields['Efetivo Total']!=null&&(!Number.isInteger(Number(r.fields['Efetivo Total']))||Number(r.fields['Efetivo Total'])<0))throw Error('Efetivo deve ser inteiro e não negativo.');const work=s.works.find(w=>w.id===r.obraId);const fields=Object.fromEntries(RDO_FIELDS.map(k=>[k,String(r.fields[k]??'')]));fields.Obra=work.name;fields['Dia da Semana']=new Intl.DateTimeFormat('pt-BR',{weekday:'long',timeZone:'UTC'}).format(new Date(fields.Data+'T12:00:00Z'));const result={id:r.id,obraId:r.obraId,fields,status:'rascunho',version:(old?.version||0)+1,updatedAt:new Date().toISOString()};if(old)s.rdos[s.rdos.indexOf(old)]=result;else s.rdos.push(result);return result;}
function seed(){const d=today();const add=n=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};return {schema:1,revision:0,works:[{id:'demo-a',name:'Obra Horizonte',city:'Uberaba / MG',company:'Construtora Exemplo',type:'Industrial'},{id:'demo-b',name:'Obra Parque',city:'Florianópolis / SC',company:'Construtora Exemplo',type:'Edificação'}],tasks:[['Conferir cotas da rede de drenagem','Engenharia','Marina Costa','alta','fazendo',-1],['Liberar frente para concretagem','Produção','Carlos Lima','alta','afazer',0],['Conferir entrega de tubos PEAD','Suprimentos','Rafael Souza','media','afazer',1],['Revisar sinalização de acesso','Segurança','Ana Ribeiro','alta','fazendo',0],['Registrar ensaio de compactação','Qualidade','Marina Costa','media','concluido',-1],['Locação de equipamento adicional','Produção','Carlos Lima','baixa','cancelado',-2]].map((a,i)=>({id:'t'+i,obraId:'demo-a',title:a[0],sector:a[1],owner:a[2],priority:a[3],status:a[4],due:add(a[5]),created:add(-5),description:'Registro fictício para avaliação do fluxo operacional.',creator:'Equipe de demonstração',history:[{at:new Date().toISOString(),from:null,to:a[4],reason:a[4]==='cancelado'?'Demanda substituída no exemplo.':'Dado demonstrativo',action:'criação'}]})),rdos:[],meetings:[]};}
globalThis.GerenciamentoCore={STATUS,RDO_FIELDS,clone,active,overdue,saveTask,saveMeeting,saveRdo,seed};
