// Módulos preservados dos arquivos fornecidos, com dados exclusivos do Gerenciamento.
const MODULE_PREFIX='gerenciamento-modulos-v2:';
const moduleKey=id=>MODULE_PREFIX+id;
function moduleBucket(id=workId){const raw=localStorage.getItem(moduleKey(id));if(raw){const b=JSON.parse(raw);if(!b||b.schema!==2)throw Error('Dados de módulos incompatíveis.');return b;}const w=state.works.find(x=>x.id===id);return {schema:2,revision:0,obra:{nome:w?.name||'',empresa:w?.company||'',local:w?.city||''},shared:{assuntos:state.tasks.filter(t=>t.obraId===id).map(taskToSource),reunioes:state.meetings.filter(m=>m.obraId===id).map(m=>({id:m.id,data:m.date,hora:m.time,assuntos:(m.snapshot||[]).map(taskToSource),participantes:m.participants||'',decisoes:m.decisions||''})),membros:[],setores:null},pauta:{},checkin:{},diario:{},connections:{service:'',webhook:''}};}
function taskToSource(t){return {id:t.id,assunto:t.title,desc:t.description||'',resp:t.owner||'',criador:t.creator||'',setor:t.sector||'',prioridade:t.priority,status:t.status,dataLanc:t.created||'',dataTerm:t.due||'',criadoEm:t.createdAt?Date.parse(t.createdAt):Date.parse((t.created||today())+'T12:00:00'),concluidoEm:t.completedAt?Date.parse(t.completedAt):undefined};}
function taskFromSource(t,id=workId){return {id:String(t.id),obraId:id,title:t.assunto||'',description:t.desc||'',owner:t.resp||'',creator:t.criador||'',sector:t.setor||'',priority:t.prioridade||'media',status:t.status,created:t.dataLanc||'',due:t.dataTerm||'',createdAt:t.criadoEm,completedAt:t.concluidoEm,history:[]};}
function persistBucket(id,b){b.revision=(b.revision||0)+1;localStorage.setItem(moduleKey(id),JSON.stringify(b));$('#saved').textContent='Salvo neste navegador';}
function sourceGet(kind,id,key){const b=moduleBucket(id);if(key.startsWith('pauta_'))key=key.slice(6);if(key.startsWith('chk_'))key=key.slice(4);let value;if(kind!=='diario'&&['assuntos','reunioes','membros','setores'].includes(key))value=b.shared[key];else if(kind==='checkin'&&key==='config')value={...(b.checkin.config||{}),obra:b.obra.nome};else if(kind==='pauta'&&key==='config')value={webhook:b.connections.webhook};else if(kind==='checkin'&&['nomesResp','nomesCriador'].includes(key))value=b.checkin[key]||b.shared.membros;else value=b[kind][key];return value===undefined||value===null?null:JSON.stringify(value);}
function sourceSet(kind,id,key,value){const b=moduleBucket(id);let k=key.replace(/^(pauta_|chk_)/,'');const data=JSON.parse(value);if(kind!=='diario'&&['assuntos','reunioes','membros','setores'].includes(k))b.shared[k]=data;else if(kind==='checkin'&&k==='config'){b.checkin.config=data;b.obra.nome=data.obra;}else if(kind==='pauta'&&k==='config'){b.connections.webhook=data.webhook||'';}else{b[kind][key]=data;if(kind==='diario'&&key==='ger_diario_state'&&data?.obra)b.obra={...b.obra,...data.obra};if(kind==='checkin')b.checkin[k]=data;}persistBucket(id,b);}
window.GerenciamentoModules={
 storage(kind,id){return {getItem:k=>sourceGet(kind,id,k),setItem:(k,v)=>sourceSet(kind,id,k,v),removeItem:k=>{const b=moduleBucket(id);delete b[kind][k];persistBucket(id,b);}};},
 getWork:id=>moduleBucket(id).obra,
 settings:id=>moduleBucket(id).connections,
 changed:()=>{},
 async request(id,path,action,body){const config=moduleBucket(id).connections;if(!config.service)throw Error('Configure o serviço próprio em Conexões.');const url=new URL(config.service);url.searchParams.set('path',path);url.searchParams.set('action',action);url.searchParams.set('obra_id',id);if(body===undefined){url.searchParams.set('obra',moduleBucket(id).obra.nome);}const response=await fetch(url,{method:body===undefined?'GET':'POST',...(body===undefined?{}:{headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...body,obra_id:id})}),signal:AbortSignal.timeout(25000)});if(!response.ok)throw Error('Falha no serviço ('+response.status+').');const data=await response.json();if(data.ok===false||data.error)throw Error(data.error||data.msg||'Operação não confirmada.');return data;},
 resize(win,height){const iframe=$('#module-frame');if(iframe?.contentWindow===win)iframe.style.height=Math.min(Math.max(Number(height)||650,650),50000)+'px';}
};
// Os indicadores e a pauta usam o mesmo conjunto de assuntos dos módulos.
const baseRender=render;
const baseTaskDialog=taskDialog;
const baseMeetingDialog=meetingDialog;
function moduleTasks(){return moduleBucket().shared.assuntos.map(t=>taskFromSource(t));}
function moduleMeetings(){return moduleBucket().shared.reunioes.map(m=>({id:String(m.id),obraId:workId,title:'Check-in de gestão',date:m.data,time:m.hora,participants:m.participantes||'',decisions:m.decisoes||'',type:'Diária',snapshot:(m.assuntos||[]).map(t=>taskFromSource(t))}));}
function moduleDiaryCount(){return Object.keys(moduleBucket().diario.ger_diario_history||{}).length;}
function mountModule(kind,tab,id){const frame=$('#module-frame');const html=MODULE_DOCUMENTS[kind];const wid=workId;const boot=`<script>window.__moduleKind=${JSON.stringify(kind)};window.__obraId=${JSON.stringify(wid)};window.__storage=parent.GerenciamentoModules.storage(window.__moduleKind,window.__obraId);window.__startTab=${JSON.stringify(tab||'')};window.__editId=${JSON.stringify(id||'')};<\/script>`;frame.srcdoc=html.replace('<!--GER-BOOT-->',boot);}
function moduleHeading(kind){const label={pauta:'Pauta de demandas',checkin:'Check-in de gestão',diario:'Diário de obras'}[kind];return `<div class="heading"><div><div class="eyebrow">${esc(work().name)}</div><h1>${label}</h1><p>${kind==='pauta'?'Cadastro, envio e acompanhamento dos assuntos.':kind==='checkin'?'Reunião, quadro, calendário e indicadores da pauta.':'Apontamento diário, recursos, relatórios e histórico.'}</p></div><div class="ger-host-actions">${kind==='diario'?'<button class="secondary" id="old-rdos">Rascunhos em texto</button>':''}<button class="secondary" data-goto="connections">Conexões</button></div></div><iframe id="module-frame" title="${label}" sandbox="allow-scripts allow-same-origin allow-modals allow-downloads allow-popups allow-popups-to-escape-sandbox" style="display:block;width:100%;border:0;min-height:650px;background:#f4f5f7"></iframe>`;}
function connectionsView(){const c=moduleBucket().connections;return `<div class="heading"><div><div class="eyebrow">CONFIGURAÇÃO DA OBRA</div><h1>Conexões e backups</h1><p>Configurações exclusivas de ${esc(work().name)}.</p></div></div><section class="panel" style="padding:24px"><h2>Serviços próprios</h2><p class="muted">As funções locais estão disponíveis. Planilha, fotos e backup na nuvem e consulta à IA precisam de um serviço configurado para o Gerenciamento.</p><form id="connections-form"><div class="form-grid">${field('service','URL do serviço do Gerenciamento',c.service,'url')}${field('webhook','URL do webhook n8n',c.webhook,'url')}</div><div class="ger-host-actions"><button class="primary">Salvar conexões</button></div></form><p class="footnote">Nenhum endereço de outro aplicativo foi incluído. O n8n só recebe dados quando você aciona Exportar.</p></section><section class="panel" style="padding:24px;margin-top:22px"><h2>Cópia completa do Gerenciamento</h2><p class="muted">Inclui as obras, os módulos, as configurações e os registros locais.</p><div class="ger-host-actions"><button class="secondary" id="full-export">Exportar arquivo</button><label class="secondary">Restaurar arquivo <input type="file" id="full-import" accept="application/json" style="display:block;margin-top:8px;max-width:260px"></label></div><p class="muted">Os backups próprios de Pauta e Diário continuam disponíveis nas abas de cadastro de cada módulo.</p></section>`;}
let moduleStart=null;
render=function(){if(!state)return;for(const w of state.works){const b=moduleBucket(w.id);if(b.obra.nome)w.name=b.obra.nome;}baseRender();if(['pauta','tasks','meetings','rdos'].includes(view)){const kind=view==='pauta'?'pauta':view==='rdos'?'diario':'checkin';$('#main').innerHTML=moduleHeading(kind);mountModule(kind,moduleStart?.tab,moduleStart?.id);moduleStart=null;}if(view==='connections'){$('#main').innerHTML=connectionsView();$('#connections-form').onsubmit=e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));for(const v of Object.values(d)){if(v&&new URL(v).protocol!=='https:')throw Error('Use uma URL HTTPS.');}const b=moduleBucket();b.connections=d;persistBucket(workId,b);toast('Configurações salvas.');}catch(err){toast(err.message,true);}};}if(view==='overview'){const count=moduleDiaryCount();const btn=$('[data-goto="rdos"].metric');if(btn){btn.querySelector('strong').textContent=String(count).padStart(2,'0');btn.querySelector('span').innerHTML='Diários no histórico <b>↗</b>';btn.querySelector('small').textContent='Registros do módulo Diário';}}};
names.connections='Conexões e backups';icons.connections='⇄';
taskDialog=function(id){moduleStart={tab:id?'cadastro':'cadastro',id};navTo('tasks');};
meetingDialog=function(){navTo('meetings');};
const oldRdoDialog=rdoDialog;
rdoDialog=function(id){if(id)return oldRdoDialog(id);navTo('rdos');};
function fullBackup(){const modules={};for(const w of state.works)modules[w.id]=moduleBucket(w.id);return {app:'Gerenciamento',schema:2,environment:'avaliacao-local',exportedAt:new Date().toISOString(),data:state,modules};}
function exportFull(){download('Gerenciamento-backup-'+today()+'.json',JSON.stringify(fullBackup(),null,2),'application/json');toast('Cópia completa exportada.');}
$('#export').onclick=exportFull;
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.id==='full-export')exportFull();if(b?.id==='old-rdos'){dialog('Rascunhos em texto da primeira versão',`<p class="muted">Os registros anteriores permanecem preservados.</p>${state.rdos.filter(r=>r.obraId===workId).map(r=>`<p>${esc(r.fields.Data)} · ${esc(r.fields.Apontador)} <button type="button" class="secondary" data-raw-rdo="${esc(r.id)}">Abrir</button></p>`).join('')||'<p>Nenhum rascunho em texto.</p>'}`,null,true);}if(b?.dataset.rawRdo){$('#dialog').close();oldRdoDialog(b.dataset.rawRdo);}});
document.addEventListener('change',async e=>{if(e.target.id!=='full-import'||!e.target.files[0])return;try{const d=JSON.parse(await e.target.files[0].text());validateFullBackup(d);if(!confirm('Restaurar este arquivo completo? Será baixada uma cópia dos dados atuais antes da substituição.'))return;exportFull();const previous=fullBackup();try{for(const [id,b] of Object.entries(d.modules||{}))localStorage.setItem(moduleKey(id),JSON.stringify(b));const next=clone(d.data);await writeDB(next,state.revision);state=next;workId=state.works[0].id;render();toast('Cópia restaurada neste navegador.');}catch(err){for(const [id,b] of Object.entries(previous.modules))localStorage.setItem(moduleKey(id),JSON.stringify(b));throw err;}}catch(err){toast(err.message,true);}e.target.value='';});
function validateFullBackup(d){if(d?.app!=='Gerenciamento'||!d.data||!Array.isArray(d.data.works)||!d.data.works.length||!['tasks','rdos','meetings'].every(k=>Array.isArray(d.data[k])))throw Error('Arquivo de Gerenciamento inválido.');for(const [id,b] of Object.entries(d.modules||{})){if(!d.data.works.some(w=>w.id===id)||b?.schema!==2||!Array.isArray(b.shared?.assuntos)||!Array.isArray(b.shared?.reunioes)||!b.obra||!b.connections)throw Error('Dados de módulos inválidos.');for(const t of b.shared.assuntos)if(!(t.status in STATUS)||!t.id||typeof t.assunto!=='string')throw Error('Demanda inválida no backup.');}}
